### ISSUE TITLE
Chat Issue!

### ISSUE THREAD

**Issue by dcflow** [kwkhaw/Layer-Parse-iOS-Swift-Example#1]
Hi guys, 

The sent pictures on chat are greyed out.
![screen shot 2015-06-11 at 1 07 31 pm](https://cloud.githubusercontent.com/assets/6751025/8105668/78d267b6-103b-11e5-89ca-fbe3592e8beb.png)

Thank you!

**Comment by kwkhaw** [comment]
Hi EMidee66, Thanks for reporting the issue. I found that the original project (objective-C version) also has the same issue. I reported the issue on that repo as well. I will try to take a look into the issue as well while waiting for the reply from Layer's guys. :-)

**Comment by kwkhaw** [comment]
Fixed in commit c4d7607

**Comment by dcflow** [comment]
Thank You!
