### ISSUE TITLE
Image Upload & Location Issue!

### ISSUE THREAD

**Issue by dcflow** [kwkhaw/Layer-Parse-iOS-Swift-Example#12]
Hi @kwkhaw ,

There is a UI problem when you have the keyboard open and you choose to upload an image, the keyboard overlaps the action view. I think this is an Atlas issue. Should I report the issue on the Atlas-iOS page? Also the location button doesn't send the location.
![screen shot 2015-10-04 at 3 20 12 pm](https://cloud.githubusercontent.com/assets/6751025/10268013/77584746-6aab-11e5-96a8-62a44b7fbe6e.png)

Thank You!

**Comment by kwkhaw** [comment]
@EMidee66 I can't reproduce the 1st issue.
Did you see the problem with the latest commit (I upgrade to Atlas 0.16.0 yesterday)?
What is your Xcode version?
Do you encounter the issue in simulator (if so, which simulator?) or your device (iOS version)?

About 2nd issue: mmm... sigh... I can't remember whether it worked previously. Probably need a bit time to check it out.

By the way, thanks for reporting the issue. :-)

**Comment by dcflow** [comment]
Hey @kwkhaw ,

I used the latest commit on Xcode 7, simulator iPhone 6/6S. So if you send an image when the keyboard is open does the alert view appear as a standard alert or as an action sheet?

Thank You!

**Comment by kwkhaw** [comment]
Hi @EMidee66 I tested it on iPhone 6s/6s Plus simulator. Below is the screencast captured with recordit.co for iPhone 6s simulator. Is it the same as what you did?

![Image of Screencast](http://g.recordit.co/4Uf31RlbMa.gif)

**Comment by dcflow** [comment]
Hey @kwkhaw ,

That's perfect. That's what should happen. Maybe there's an issue
with my simulator. I fixed it by adding this code at ATLConversationViewController
    `[self.view endEditing:(YES)];` line 556.

Thank You!

**Comment by kwkhaw** [comment]
@EMidee66 Thanks for the info!
As for the location issue, i will check it out another time. :-)
