### ISSUE TITLE
Images not being shown to the recipient when sent

### ISSUE THREAD

**Issue by UNLUCKYME** [kwkhaw/Layer-Parse-iOS-Swift-Example#13]
The user sending images can clearly see the picture they uploaded, but the recipient only sees a blank grey box. 

Not sure at all why this is the case.

**Comment by kwkhaw** [comment]
Probably u can try to increase the autodownloadMaximumContentSize in AppDelegate.swift?

**Comment by UNLUCKYME** [comment]
Perfect
