### ISSUE TITLE
Problem with archiving this project.

### ISSUE THREAD

**Issue by kokernutz** [kwkhaw/Layer-Parse-iOS-Swift-Example#14]
First off, thanks for providing this project to the community.

My problem is I cannot archive this project. Using 0.39.0 I do a pod install, update the bundle identifier to something that's valid for my developer account, and I get a few errors at the end of the build phase:

```
/Users/bsk/Documents/Layer-Parse-iOS-Swift-Example-master-2/Pods/Headers/Public/Atlas/Atlas.h:32:9: 'ATLAddressBarViewController.h' file not found
```

and

```
#import <Atlas/Atlas.h>
        ^
/Users/bsk/Downloads/Layer-Parse-iOS-Swift-Example-master-2/Pods/Headers/Public/Atlas/Atlas.h:32:9: error: 'ATLAddressBarViewController.h' file not found
#import "ATLAddressBarViewController.h"
        ^
<unknown>:0: error: failed to import bridging header '/Users/bsk/Downloads/Layer-Parse-iOS-Swift-Example-master-2/Code/Layer-Parse-iOS-Swift-Example-Bridging-Header.h'
```

I find this odd as I can build and run the project on or device or in the simulator. I have not modified the project in any way other than doing a pod install and updating the bundle identifier.

Why do I care about archiving this demo project? Because the same issue is happening in my real project. I decided to try archiving the unmodified demo project and ran into the same issues. (Sanity restored!)

I have tried updating the Podfile to use newer versions of the Atlas/Layer cocoapods, but there seems to be an issue with using those with swift.

Thanks for your input.

**Comment by kokernutz** [comment]
I fixed my issues that I was having with the new versions of LayerKit and Atlas when using Swift. (No more bridging header, just include the framework in each file that needs it.)

**Comment by kwkhaw** [comment]
Hi @kokernutz thanks for your update. :)
