### ISSUE TITLE
Swift 2.1 : Command failed due to signal: Segmentation fault: 11

### ISSUE THREAD

**Issue by sysadminPSQ** [kwkhaw/Layer-Parse-iOS-Swift-Example#15]
I just updated Xcode to 7.1 which includes update to Swift 2.1 after which i am getting a segmentation fault error when building the project.

After digging around i was able to figure out that this was because of a type cast issue in ConversationViewController.swift

I have tried everything but nothing seems to work. Could you please help me out on this?

Here is the code below

```
let status: LYRRecipientStatus! = LYRRecipientStatus(rawValue: Int(recipientStatusDict[participantAsString]!.unsignedIntegerValue))  
```

**Comment by kwkhaw** [comment]
Hi @sysadminPSQ I tried to build to project with Xcode 7.1 and run the app the simulator, I didn't encounter the problem as you mentioned. Could you provide me more info?

**Comment by sysadminPSQ** [comment]
@kwkhaw 

Hi, 

Sorry for the late reply.

It looks like when i run your project on its own, it builds and runs perfectly fine.

The issue occurs when i am using your example code and files in another project of my own. And this error only appeared after Xcode updated 7.1 came in and was working fine even in my project prior Xcode 7.1. 

I am not sure how to go about this, or am i missing something?

**Comment by kwkhaw** [comment]
@sysadminPSQ Understood. However, I can't help much if I can't reproduce the issue.
Did you try to clean and rebuild the project?
Also, probably can try to remove `Pods/` and `Podfile.lock`, and then reinstall the pods?

**Comment by sysadminPSQ** [comment]
@kwkhaw 

Tried everything, still the same error.

Here is a sample of my Podfile

``` Swift
platform :ios, '8.0'
target 'Messaging' do
    pod 'LayerKit'
    pod 'Atlas'
    pod 'Parse'
    pod 'ParseUI'
    pod 'SVProgressHUD'
end  
```

Also attaching a screenshot of the error.
<img width="835" alt="error" src="https://cloud.githubusercontent.com/assets/13114977/10874934/8c3d0440-8152-11e5-8b6b-e89099dce662.png">

Hope this helps.

**Comment by kwkhaw** [comment]
@sysadminPSQ You should set the version of each pod. Without specifying version, every time you run `pod install`, you will install the latest pods, which might break the build.

Please use the following versions and try again. Note: Now Atlas pod already includes LayerKit, so you don't need to specify LayerKit in the Podfile anymore.

```
  pod 'Atlas', '~> 1.0.14'
  pod 'Parse', '~> 1.8.0'
  pod 'ParseUI', '~> 1.1.6'
  pod 'SVProgressHUD', '~> 1.1.3'
```
