### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by isacikgoz** [kwkhaw/Layer-Parse-iOS-Swift-Example#18]
After creating a group conversation, I added my simulator as a participant from my actual phone, the app on the simulated crashes while starting. The error is 

`fatal error: unexpectedly found nil while unwrapping an Optional value`

It is caused by the line 

```
func conversationListViewController(conversationListViewController: ATLConversationListViewController!, avatarItemForConversation conversation: LYRConversation!) -> ATLAvatarItem! {
    let userID: String = conversation.lastMessage.sender.userID // <- this line throws nil pointer error
    if userID == PFUser.currentUser()!.objectId {
        return PFUser.currentUser()
    }
    let user: PFUser? = UserManager.sharedManager.cachedUserForUserID(userID)
    if user == nil {
        UserManager.sharedManager.queryAndCacheUsersWithIDs([userID], completion: { (participants, error) in
            if participants != nil && error == nil {
                self.reloadCellForConversation(conversation)
            } else {
                print("Error querying for users: \(error)")
            }
        })
    }
    return user;
}
```

There are 2 message in the conversation but this method call for 4 times, at the 4. step `conversation.lastMessage` is nil

**Comment by isacikgoz** [comment]
```
    if conversation.lastMessage == nil {
        return nil
    }
```

after added this into the begging of  the function everything seems to be fine, I just started to play with Layer 5 mins ago maybe this is not the right solution :)

**Comment by kwkhaw** [comment]
@isacikgoz Thanks for reporting the issue and your analysis. Recently, I'm a bit busy and don't really have time to contribute to the project. It would be great if you would like to submit a PR for fix. :-)

**Comment by isacikgoz** [comment]
ok, i will :)
