### ISSUE TITLE
Participant Issue!

### ISSUE THREAD

**Issue by dcflow** [kwkhaw/Layer-Parse-iOS-Swift-Example#2]
If I select a conversation before the chat name has been updated then **return user!** line 58 in  ConversationViewController throws an error because it's nil. Maybe because **queryAndCacheUsersWithIDs**  is done on the background and it hasn't finished yet.

**Comment by kwkhaw** [comment]
HI EMidee66, I debugged a bit on this issue. I was able to reproduce the issue by using simulator with slow network (with the help of Network Link Conditioner). I compared my code with the original Objective-C version. Seems like I should not force unwrap the **user** at line 58 and the return type of the delegate function shall be optional **ATLParticipant?**. However, even after I made the change, it still crashed in ATLConversationViewController.m, line 966. Also, I was able to reproduced the issue in the Objective-C sample app, so seems like the original project also has the same issue. I will see how can I deal with this issue later. Thanks again for reporting the bug. :+1:

**Comment by kwkhaw** [comment]
Fixed in commit a6a56624bf736c744b0493748db00feaf308205d
For now, I just prevent the user from selecting the conversation if the participants' name are not resolved yet. I will update this if I can find a better solution.

**Comment by dcflow** [comment]
Thank you @kwkhaw.

**Comment by kwkhaw** [comment]
@EMidee66 Welcome. :smiley:

**Comment by Deviz** [comment]
Thanks for the fix kwkhaw, but this leads to another issue. If you close the app by pressing home button, and open the app again, it doesn't want to select the conversation.
