### ISSUE TITLE
Changing ATLAvatarItem

### ISSUE THREAD

**Issue by bopeola21** [kwkhaw/Layer-Parse-iOS-Swift-Example#23]
I'm having trouble changing the Avatar images in the ConversationListViewController from initials to actual user images. I tried using ATLAvatarImageView, which changed the images but was not changing them correctly. The ATLAvatarItem image properties are readonly as well. Can you point me in the right direction? Thanks.

I'm editing inside this method.

```
func conversationListViewController(conversationListViewController: ATLConversationListViewController!, avatarItemForConversation conversation: LYRConversation!) -> ATLAvatarItem! {}
```

**Comment by bopeola21** [comment]
I figured out the answer. For anyone else having this issue your subclass has to conform to the ATLAvatarItem protocol. Look up file name PFUser+ATLParticipant.swift to see which properties are needed to conform to this protocol.

**Comment by kwkhaw** [comment]
@bopeola21 Thanks for the update!
