### ISSUE TITLE
Error: contextual type for closure argument list accepts 3 arguments,but 2 were specified

### ISSUE THREAD

**Issue by akshaysanthanam** [kwkhaw/Layer-Parse-iOS-Swift-Example#25]
Hi,
I have constantly been having this issue inspite of several attempts.

Thanks,

**Comment by ashyxz** [comment]
Having the same problem after updating from 0.18.1. The function signature in [0.19.0](https://github.com/layerhq/releases-ios/blob/v0.19.4/LayerKit.framework/Headers/LYRClient.h) + has changed
