### ISSUE TITLE
Compiler Error

### ISSUE THREAD

**Issue by agodoy21** [kwkhaw/Layer-Parse-iOS-Swift-Example#3]
Hello,

I did the complete install and cannot get it to compile. Please view attached pic. I did the pod install and even a pod update, etc. Any thoughts? Am I missing something?

Thanks,

AG

<img width="1005" alt="screen shot 2015-07-09 at 11 27 58 pm" src="https://cloud.githubusercontent.com/assets/942088/8611105/63f337fe-2692-11e5-9ad4-6f72c8f950e3.png">

**Comment by kwkhaw** [comment]
Hi Andres,
I think Layer has made some public API changes since v0.15.0. You may specify the version of LayerKit to version before v0.15.0 in the Podfile. Sorry that I don't have access to XCode now to fix the issue. I will fix that later.

**Comment by agodoy21** [comment]
Hi kwkhaw,

Thanks, that worked!

I realize this might a Parse issue, but any thoughts on the error below? Thanks again,

Andres

![screen shot 2015-07-10 at 1 06 34 pm](https://cloud.githubusercontent.com/assets/942088/8622944/ba313630-2704-11e5-8b4a-8a769f96a1e4.png)

**Comment by kwkhaw** [comment]
Hi agodoy21,
from the error message, I think probably you missed out the step 5 "Add the Layer Parse Module to your Parse Cloud Code to serve as an authentication manager." in the setup. You may refer to this repo for the instruction. https://github.com/layerhq/layer-parse-module.

Please try it out and open another issue if it is still not working.

By the way, I has made the changes in Podfile to specify the version for each pod to avoid compatibility issues in the future.
Thanks for reporting the issue. :-)
