### ISSUE TITLE
I've having some problems implements push notifications.

### ISSUE THREAD

**Issue by UNLUCKYME** [kwkhaw/Layer-Parse-iOS-Swift-Example#7]
When I attempt to enable push notification, I seem to run into serious issues. The docs are for obj-c only and while I powered through and made a very functional swift version, with the help of this project of course, I can't for the life of me get push notifications to work properly. 

If anyone has gotten it to work, can you share what you did to make it so?

**Comment by kwkhaw** [comment]
Hi @UNLUCKYME , probably we can have few options to resolve your issue:
1. Share your code somewhere and with details of the issues you encountered.
2. There is a PR in the original (Objective-C) project implementing the Push. https://github.com/layerhq/Layer-Parse-iOS-Example/pull/18. I will try to port it over to Swift later (By saying that, sounds like I know how to do it. :stuck_out_tongue: Sorry, but I don't know until I really work on it.)
3. I ported Anypic to Swift https://github.com/kwkhaw/SwiftAnyPic, which has the Push Notification feature. Again, I don't have the chance to try it out yet. Probably you can refer to the code and let me know if it works. :-)

**Comment by kwkhaw** [comment]
Hi @UNLUCKYME , I have ported the push notification logic from the original (Objective-C) project in the latest commit.
Hope the information below will help you:
- Push Notification only work on the iOS device, you can't test it with Simulator. (I just learnt that recently). :smile: 
- Follow the instructions in Layer's documentation: https://developer.layer.com/docs/ios/guides#push-notification

Let me know if you still can't get it to work. I think I understand push notification better now.
